### ISSUE TITLE
resource request key format

### ISSUE THREAD

**Issue by 5cat** [nebuly-ai/nos#20]
To request a GPU with a 10g the following key/value is used 
```
resources:
  limits:
    nvidia.com/gpu-10gb: 1
```
Would it make more sense to do the following instead
```
resources:
  limits:
    nvidia.com/gpu-memory: "10Gi"
    nvidia.com/gpu: 1
```
