### ISSUE TITLE
mig-agent pod failure

### ISSUE THREAD

**Issue by likku123** [nebuly-ai/nos#21]
Hi,

I am seeing the below error in nebuly-nos-nebuly-nos-mig-agent pod.

{"level":"info","ts":1678537855.2905262,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1678537855.2921324,"logger":"setup","msg":"Initializing NVML client"}
{"level":"info","ts":1678537855.2921576,"logger":"setup","msg":"Checking MIG-enabled GPUs"}
{"level":"info","ts":1678537855.450721,"logger":"setup","msg":"Cleaning up unused MIG resources"}
{"level":"error","ts":1678537855.5242505,"logger":"setup","msg":"unable to initialize agent","error":"[code: generic  err: unable to get allocatable resources from Kubelet gRPC socket: rpc error: code = Unimplemented desc = unknown method GetAllocatableResources for service v1.PodResourcesLister]","stacktrace":"main.main\n\t/workspace/migagent.go:119\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

Please let me know what information is needed from my side and also any pointers on why we get this error will be greatly appreciated.

Thanks

**Comment by likku123** [comment]
Also I am seeing the below error in nvidia-device-plugin-daemonset pod

2023/03/12 02:49:25 Starting FS watcher.
2023/03/12 02:49:25 Starting OS watcher.
2023/03/12 02:49:25 Starting Plugins.
2023/03/12 02:49:25 Loading configuration.
2023/03/12 02:49:25 Updating config with default resource matching patterns.
2023/03/12 02:49:25
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "mixed",
    "failOnInitError": true,
    "nvidiaDriverRoot": "/run/nvidia/driver",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": true,
      "deviceListStrategy": "envvar",
      "deviceIDStrategy": "uuid"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ],
    "mig": [
      {
        "pattern": "1g.10gb",
        "name": "nvidia.com/mig-1g.10gb"
      },
      {
        "pattern": "2g.20gb",
        "name": "nvidia.com/mig-2g.20gb"
      },
      {
        "pattern": "3g.40gb",
        "name": "nvidia.com/mig-3g.40gb"
      },
      {
        "pattern": "4g.40gb",
        "name": "nvidia.com/mig-4g.40gb"
      },
      {
        "pattern": "7g.80gb",
        "name": "nvidia.com/mig-7g.80gb"
      },
      {
        "pattern": "1g.10gb+me",
        "name": "nvidia.com/mig-1g.10gb.me"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {}
  }
}
2023/03/12 02:49:25 Retreiving plugins.
2023/03/12 02:49:25 Detected NVML platform: found NVML library
2023/03/12 02:49:25 Detected non-Tegra platform: /sys/devices/soc0/family file not found
2023/03/12 02:49:25 Error: error starting plugins: error getting plugins: unable to load resource managers to manage plugin devices: failed to construct NVML resource managers: error building device map: error building device map from config.resources: invalid MIG configuration: At least one device with migEnabled=true was not configured correctly: error visiting device: device 0 has an invalid MIG configuration


Any help or pointers is highly appreciated.

Thank you.

**Comment by Telemaco019** [comment]
Hi @likku123, thank you for raising the issue! Could you please provide which Kubernetes version are you using? 

Regarding your first point, it seems like the MIG agent is not able to fetch the available resources from the Kubelet. It does that by using the [GetAllocatableResources](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-getallocatableresources) gRPC endpoint, which is available starting from k8s v1.23. Older k8s versions do not provide this endpoint, so the MIG agent won't be able to work. 

The error log you are getting from the nvidia-device-plugin DaemonSet occurs when there is a GPU with MIG mode enabled but without any MIG device. This is because the nvidia-device-plugin expects that all MIG-enabled GPUs must have at least one MIG device, otherwise it considers the configuration invalid.  This is the expected behaviour it does not prevent `nos` from creating the MIG devices on that node. As soon as `nos` creates the first MIG device, the device plugin is restarted and the configuration is considered valid. 

We should update the documentation with this information. Thanks for bringing this to my attention!

**Comment by likku123** [comment]
Hi @Telemaco019,

Kubernetes version I am using right now is v1.20.8.

Any other workaround to make the MIG agent up in k8s v1.20.8?

Also,when I try to spin up a pod with below requests in yaml

limits:
   nvidia.com/mig-1g.10gb: 1

I see the below error in nebuly-nos-nebuly-nos-gpu-partitioner pod.

"error":"model \"NVIDIA-A100-SXM4-80GB\" is not associated with any known GPU","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}

Are these errors occurring because of MIG-agent failure?

Thanks

**Comment by Telemaco019** [comment]
The MIG Agent requires that endpoint for retrieving the MIG devices exposed on each node, each with its device ID and its status (e.g. used or free) so that nos can use this information for choosing the right partitioning state. Unfortunately, I don't see any other way for getting that information right now. I can only suggest upgrading k8s to a supported version starting from 1.23. 

Regarding the error you are getting from the GPU Partitioner - It is not related to the MIG-agent failure. The issue is that nos does not know the set of available MIG geometries for that specific GPU model, as 100-SMX4-80GB is not included in the default value of [knownMigGeometries](https://github.com/nebuly-ai/nos/blob/main/helm-charts/nos/values.yaml#L317) in the Helm chart.

I'll include that model too in the next release, thank you for spotting the issue! At the moment, you can quickly fix the issue by providing the following values.yaml to the Helm installation chart: 
```yaml
knownMigGeometries:
  - models: [ "A30" ]
    allowedGeometries:
      - 1g.6gb: 4
      - 1g.6gb: 2
        2g.12gb: 1
      - 2g.12gb: 2
      - 4g.24gb: 1
  - models: [ "A100-SXM4-40GB", "NVIDIA-A100-40GB-PCIe" ]
    allowedGeometries:
      - 1g.5gb: 7
      - 1g.5gb: 5
        2g.10gb: 1
      - 1g.5gb: 3
        2g.10gb: 2
      - 1g.5gb: 1
        2g.10gb: 3
      - 1g.5gb: 2
        2g.10gb: 1
        3g.20gb: 1
      - 2g.10gb: 2
        3g.20gb: 1
      - 1g.5gb: 3
        3g.20gb: 1
      - 1g.5gb: 1
        2g.10gb: 1
        3g.20gb: 1
      - 3g.20gb: 2
      - 1g.5gb: 3
        4g.20gb: 1
      - 1g.5gb: 1
        2g.10gb: 1
        4g.20gb: 1
      - 7g.40gb: 1
  - models: [ "NVIDIA-A100-SXM4-80GB", "NVIDIA-A100-80GB-PCIe" ]
    allowedGeometries:
      - 1g.10gb: 7
      - 1g.10gb: 5
        2g.20gb: 1
      - 1g.10gb: 3
        2g.20gb: 2
      - 1g.10gb: 1
        2g.20gb: 3
      - 1g.10gb: 2
        2g.20gb: 1
        3g.40gb: 1
      - 2g.20gb: 2
        3g.20gb: 1
      - 1g.10gb: 3
        3g.40gb: 1
      - 1g.10gb: 1
        2g.20gb: 1
        3g.40gb: 1
      - 3g.40gb: 2
      - 1g.10gb: 3
        4g.40gb: 1
      - 1g.10gb: 1
        2g.20gb: 1
        4g.40gb: 1
      - 7g.79gb: 1
``` 

Hope this helps!

**Comment by likku123** [comment]
@Telemaco019 

Thanks a lot for detail explanation. I think only option left now is to upgrade k8s to 1.23 . I'll try to work on that part and will let you know if I find anything new.

Thanks.

**Comment by likku123** [comment]
@Telemaco019 

I have updated to k8s 1.23 version and now I don't see any errors.

Basically I am deploying nebuly-nos via fluxcd. One thing I have observed is what ever I have update in values.yaml file it's not getting updated.

For example I have implemented your suggestion of adding model ( NVIDIA-A100-SXM4-80GB) model to values.yaml but when I deploy it it's actually not reflecting the changes.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nebuly-nos
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nebuly-nos
  chart:
    spec:
      chart: nos
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: nebuly-nos-charts
        namespace: flux-system
      interval: 5m
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: True
  values:
    knownMigGeometries:
      - models: [ "A30" ]
        allowedGeometries:
          - 1g.6gb: 4
          - 1g.6gb: 2
            2g.12gb: 1
          - 2g.12gb: 2
          - 4g.24gb: 1
      - models: [ "A100-SXM4-40GB", "NVIDIA-A100-40GB-PCIe" ]
        allowedGeometries:
          - 1g.5gb: 7
          - 1g.5gb: 5
            2g.10gb: 1
          - 1g.5gb: 3
            2g.10gb: 2
          - 1g.5gb: 1
            2g.10gb: 3
          - 1g.5gb: 2
            2g.10gb: 1
            3g.20gb: 1
          - 2g.10gb: 2
            3g.20gb: 1
          - 1g.5gb: 3
            3g.20gb: 1
          - 1g.5gb: 1
            2g.10gb: 1
            3g.20gb: 1
          - 3g.20gb: 2
          - 1g.5gb: 3
            4g.20gb: 1
          - 1g.5gb: 1
            2g.10gb: 1
            4g.20gb: 1
          - 7g.40gb: 1
      - models: [ "NVIDIA-A100-SXM4-80GB", "NVIDIA-A100-80GB-PCIe" ]
        allowedGeometries:
          - 1g.10gb: 7
          - 1g.10gb: 5
            2g.20gb: 1
          - 1g.10gb: 3
            2g.20gb: 2
          - 1g.10gb: 1
            2g.20gb: 3
          - 1g.10gb: 2
            2g.20gb: 1
            3g.40gb: 1
          - 2g.20gb: 2
            3g.20gb: 1
          - 1g.10gb: 3
            3g.40gb: 1
          - 1g.10gb: 1
            2g.20gb: 1
            3g.40gb: 1
          - 3g.40gb: 2
          - 1g.10gb: 3
            4g.40gb: 1
          - 1g.10gb: 1
            2g.20gb: 1
            4g.40gb: 1
          - 7g.79gb: 1
```

```
kubectl describe configmap nebuly-nos-nebuly-nos-gpu-partitioner-known-mig-geometries
Name:         nebuly-nos-nebuly-nos-gpu-partitioner-known-mig-geometries
Namespace:    nebuly-nos
Labels:       app.kubernetes.io/component=gpu-partitioner
              app.kubernetes.io/instance=nebuly-nos-nebuly-nos
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=nos-gpu-partitioner
              app.kubernetes.io/part-of=nos
              app.kubernetes.io/version=0.1.0
              helm.sh/chart=nos-0.1.0
              helm.toolkit.fluxcd.io/name=nebuly-nos
              helm.toolkit.fluxcd.io/namespace=flux-system
Annotations:  meta.helm.sh/release-name: nebuly-nos-nebuly-nos
              meta.helm.sh/release-namespace: nebuly-nos

Data
====
known_mig_geometries.yaml:
----
- allowedGeometries:
  - 1g.6gb: 4
  - 1g.6gb: 2
    2g.12gb: 1
  - 2g.12gb: 2
  - 4g.24gb: 1
  models:
  - A30
- allowedGeometries:
  - 1g.5gb: 7
  - 1g.5gb: 5
    2g.10gb: 1
  - 1g.5gb: 3
    2g.10gb: 2
  - 1g.5gb: 1
    2g.10gb: 3
  - 1g.5gb: 2
    2g.10gb: 1
    3g.20gb: 1
  - 2g.10gb: 2
    3g.20gb: 1
  - 1g.5gb: 3
    3g.20gb: 1
  - 1g.5gb: 1
    2g.10gb: 1
    3g.20gb: 1
  - 3g.20gb: 2
  - 1g.5gb: 3
    4g.20gb: 1
  - 1g.5gb: 1
    2g.10gb: 1
    4g.20gb: 1
  - 7g.40gb: 1
  models:
  - A100-SXM4-40GB
  - NVIDIA-A100-40GB-PCIe
- allowedGeometries:
  - 1g.10gb: 7
  - 1g.10gb: 5
    2g.20gb: 1
  - 1g.10gb: 3
    2g.20gb: 2
  - 1g.10gb: 1
    2g.20gb: 3
  - 1g.10gb: 2
    2g.20gb: 1
    3g.40gb: 1
  - 2g.20gb: 2
    3g.20gb: 1
  - 1g.10gb: 3
    3g.40gb: 1
  - 1g.10gb: 1
    2g.20gb: 1
    3g.40gb: 1
  - 3g.40gb: 2
  - 1g.10gb: 3
    4g.40gb: 1
  - 1g.10gb: 1
    2g.20gb: 1
    4g.40gb: 1
  - 7g.79gb: 1
  models:
  - NVIDIA-A100-80GB-PCIe
```

AM I missing anything here? Only difference I see I have implemented helm chart deployment via fluxcd using URLs and using OCI is my first time.

Thank you for all the help till now.

**Comment by Telemaco019** [comment]
Hi @likku123, thank you for the follow-up! I'm glad to hear it works now with k8s 1.23 :) 

There is a little typo in the values you are providing to the Helm chart: the `knownMigGeometries` field should be indented under the field `gpuPartitioner`, and not at the root level. The correct `HelmRelease` resource should look like this:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nebuly-nos
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nebuly-nos
  chart:
    spec:
      chart: nos
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: nebuly-nos-charts
        namespace: flux-system
      interval: 5m
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: True
  values:
    gpuPartitioner:
      knownMigGeometries:
        - models: [ "A30" ]
          allowedGeometries:
            - 1g.6gb: 4
            - 1g.6gb: 2
              2g.12gb: 1
            - 2g.12gb: 2
            - 4g.24gb: 1
        - models: [ "A100-SXM4-40GB", "NVIDIA-A100-40GB-PCIe" ]
          allowedGeometries:
            - 1g.5gb: 7
            - 1g.5gb: 5
              2g.10gb: 1
            - 1g.5gb: 3
              2g.10gb: 2
            - 1g.5gb: 1
              2g.10gb: 3
            - 1g.5gb: 2
              2g.10gb: 1
              3g.20gb: 1
            - 2g.10gb: 2
              3g.20gb: 1
            - 1g.5gb: 3
              3g.20gb: 1
            - 1g.5gb: 1
              2g.10gb: 1
              3g.20gb: 1
            - 3g.20gb: 2
            - 1g.5gb: 3
              4g.20gb: 1
            - 1g.5gb: 1
              2g.10gb: 1
              4g.20gb: 1
            - 7g.40gb: 1
        - models: [ "NVIDIA-A100-SXM4-80GB", "NVIDIA-A100-80GB-PCIe" ]
          allowedGeometries:
            - 1g.10gb: 7
            - 1g.10gb: 5
              2g.20gb: 1
            - 1g.10gb: 3
              2g.20gb: 2
            - 1g.10gb: 1
              2g.20gb: 3
            - 1g.10gb: 2
              2g.20gb: 1
              3g.40gb: 1
            - 2g.20gb: 2
              3g.20gb: 1
            - 1g.10gb: 3
              3g.40gb: 1
            - 1g.10gb: 1
              2g.20gb: 1
              3g.40gb: 1
            - 3g.40gb: 2
            - 1g.10gb: 3
              4g.40gb: 1
            - 1g.10gb: 1
              2g.20gb: 1
              4g.40gb: 1
            - 7g.79gb: 1
```
Hope this helps! 

(btw, I've updated the default values of the chart for including also the model NVIDIA-A100-SXM4-80GB  in the allowed geometries, so with the next minor release 0.1.1 it won't be necessary to customize this value anymore)

**Comment by likku123** [comment]
Hi @Telemaco019 
Sorry to bother you again but right now I am stuck at a place where I don't have any clue to move forward.

I still see the below error after installing nos and also the pod going into crash loop back error.

`kubectl logs nvidia-device-plugin-daemonset-md7t8
2023/03/28 15:49:23 Starting FS watcher.
2023/03/28 15:49:24 Starting OS watcher.
2023/03/28 15:49:24 Starting Plugins.
2023/03/28 15:49:24 Loading configuration.
2023/03/28 15:49:24 Updating config with default resource matching patterns.
2023/03/28 15:49:24
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "mixed",
    "failOnInitError": true,
    "nvidiaDriverRoot": "/",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": true,
      "deviceListStrategy": "envvar",
      "deviceIDStrategy": "uuid"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ],
    "mig": [
      {
        "pattern": "1g.10gb",
        "name": "nvidia.com/mig-1g.10gb"
      },
      {
        "pattern": "2g.20gb",
        "name": "nvidia.com/mig-2g.20gb"
      },
      {
        "pattern": "3g.40gb",
        "name": "nvidia.com/mig-3g.40gb"
      },
      {
        "pattern": "4g.40gb",
        "name": "nvidia.com/mig-4g.40gb"
      },
      {
        "pattern": "7g.80gb",
        "name": "nvidia.com/mig-7g.80gb"
      },
      {
        "pattern": "1g.10gb+me",
        "name": "nvidia.com/mig-1g.10gb.me"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {}
  }
}
2023/03/28 15:49:24 Retreiving plugins.
2023/03/28 15:49:24 Detected NVML platform: found NVML library
2023/03/28 15:49:24 Detected non-Tegra platform: /sys/devices/soc0/family file not found
2023/03/28 15:49:24 Error: error starting plugins: error getting plugins: unable to load resource managers to manage plugin devices: failed to construct NVML resource managers: error building device map: error building device map from config.resources: invalid MIG configuration: At least one device with migEnabled=true was not configured correctly: error visiting device: device 0 has an invalid MIG configuration
`

` kubectl describe pod nvidia-device-plugin-daemonset-md7t8
Name:                 nvidia-device-plugin-daemonset-md7t8
Namespace:            gpu-operator-resources
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 abc.xyz.com/10.0.0.24
Start Time:           Tue, 28 Mar 2023 15:28:02 +0000
Labels:               app=nvidia-device-plugin-daemonset
                      app.kubernetes.io/managed-by=gpu-operator
                      controller-revision-hash=5b7fb6c7d4
                      helm.sh/chart=gpu-operator-v22.9.2
                      pod-template-generation=1
Annotations:          kubernetes.io/psp: psp-no-restriction
Status:               Running
IP:                   100.96.170.250
IPs:
  IP:           100.96.170.250
Controlled By:  DaemonSet/nvidia-device-plugin-daemonset
Init Containers:
  toolkit-validation:
    Container ID:  containerd://427d3223b20d2c0b3d409f0b918249dfdf1a26545d768cc76c82623f1c5455e2
    Image:         nvcr.io/nvidia/cloud-native/gpu-operator-validator:v22.9.2
    Image ID:      nvcr.io/nvidia/cloud-native/gpu-operator-validator@sha256:00f1476548fbed9ee01961443a73bf65396c2e8bb2b84426f949dd56cb4d14cd
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 28 Mar 2023 15:28:04 +0000
      Finished:     Tue, 28 Mar 2023 15:28:04 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gqxzw (ro)
Containers:
  nvidia-device-plugin:
    Container ID:  containerd://3c0850a8fb9cdcd8700b30a8a709c953ae9a0cab573ab9e14fa63e07384bcc83
    Image:         nvcr.io/nvidia/k8s-device-plugin:v0.13.0-ubi8
    Image ID:      nvcr.io/nvidia/k8s-device-plugin@sha256:9c17d3a907eb77eb8f7b4f3faf52d8352e4252af92003f828083f80d629bd2c3
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
    Args:
      [[ -f /run/nvidia/validations/host-driver-ready ]] && driver_root=/ || driver_root=/run/nvidia/driver; export NVIDIA_DRIVER_ROOT=$driver_root; exec nvidia-device-plugin;
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 28 Mar 2023 15:54:34 +0000
      Finished:     Tue, 28 Mar 2023 15:54:34 +0000
    Ready:          False
    Restart Count:  10
    Environment:
      PASS_DEVICE_SPECS:           true
      FAIL_ON_INIT_ERROR:          true
      DEVICE_LIST_STRATEGY:        envvar
      DEVICE_ID_STRATEGY:          uuid
      NVIDIA_VISIBLE_DEVICES:      all
      NVIDIA_DRIVER_CAPABILITIES:  all
      MIG_STRATEGY:                mixed
      NVIDIA_MIG_MONITOR_DEVICES:  all
    Mounts:
      /run/nvidia from run-nvidia (rw)
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gqxzw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:  Directory
  kube-api-access-gqxzw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.deploy.device-plugin=true
Tolerations:                 gpugate:NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
                             nvidia.com/gpu:NoSchedule op=Exists
                             ondemand:NoSchedule op=Exists
                             pre-release:NoSchedule op=Exists
                             reserved:NoSchedule op=Exists
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  31m                  default-scheduler  Successfully assigned gpu-operator-resources/nvidia-device-plugin-daemonset-md7t8 to abc.xyz.com/10.0.0.24
  Normal   Pulled     31m                  kubelet            Container image "nvcr.io/nvidia/cloud-native/gpu-operator-validator:v22.9.2" already present on machine
  Normal   Created    31m                  kubelet            Created container toolkit-validation
  Normal   Started    31m                  kubelet            Started container toolkit-validation
  Normal   Started    30m (x4 over 31m)    kubelet            Started container nvidia-device-plugin
  Normal   Pulled     29m (x5 over 31m)    kubelet            Container image "nvcr.io/nvidia/k8s-device-plugin:v0.13.0-ubi8" already present on machine
  Normal   Created    29m (x5 over 31m)    kubelet            Created container nvidia-device-plugin
  Warning  BackOff    90s (x139 over 31m)  kubelet            Back-off restarting failed container
`

Am I missing any thing here ?

Is this similar to this bug you have raised https://github.com/nebuly-ai/nos/issues/25 ?

**Comment by Telemaco019** [comment]
Hello @likku123, no worries at all! And thank you for the detailed information!

Yes, it seems the problem is related to #25. However, if your node has just a single GPU, then these error logs should not affect GPU partitioning.  Even though initially the nvidia-device-plugin Pod crashes, when `nos` creates the requested MIG resource the device-plugin is restarted and it should advertise the new MIG resources correctly. 

You can try to submit a Pod requesting some MIG resources: after at most ~30 seconds the requested resources should be created and the device-plugin Pod should run properly. 

However, we have already fixed #25 on the branch main, so installing the latest version of the GPU partitioner container should solve the error logs you are seeing, as GPUs are now initialized with the largest available MIG devices. You can install the latest version by adding the following entry to your `HelmRelease` values:
```yaml
gpuPartitioner:
    image:
        tag: latest
```

Let me know if you need any help!
