### ISSUE TITLE
Partitioner renders malformed device-plugin ConfigMap value which breaks GFD, causing Pods to be Pending forever

### ISSUE THREAD

**Issue by zerodayyy** [nebuly-ai/nos#41]
In `internal/partitioning/mps/partitioner.go`, in `ToPluginConfig` function, Config struct is used from `github.com/NVIDIA/k8s-device-plugin/api/config/v1` package. This struct, while containing nested structs, does not use struct pointers, which causes YAML/JSON Marshal function to render "empty" structs as empty map/object, instead of omitting them. This results in following config value:

```yaml
flags:
  failOnInitError: null
  gdsEnabled: null
  migStrategy: none
  mofedEnabled: null
resources:
  gpus: null
sharing:
  mps:
    failRequestsGreaterThanOne: true
    resources:
    - devices:
      - "0"
      memoryGB: 10
      name: nvidia.com/gpu
      rename: gpu-10gb
      replicas: 2
  timeSlicing: {}
version: v1
```

This behavior is explained [here](https://www.sohamkamani.com/golang/omitempty/#values-that-cannot-be-omitted).

There are checks in the same package for empty `resources` within `sharing.ts` when unmarshalling raw data, as shown [here](https://github.com/NVIDIA/k8s-device-plugin/blob/4f261c04a21e34abb3d34345e34c795ecfaac0de/api/config/v1/replicas.go#L148):

```golang
	resources, exists := ts["resources"]
	if !exists {
		return fmt.Errorf("no resources specified")
	}
```

Essentially, when new partitioning config is applied, malformed data cause GFD container to crash indefinitely with `no resources specified` error, until empty `timeSlicing: {}` is removed from ConfigMap, which resolves the error.

I think it makes sense to give up `github.com/NVIDIA/k8s-device-plugin/api/config/v1` package in favor of Nebuly's fork of k8s-device-plugin, and fix this issue there by eiher removing the checks as they don't work properly, or tweaking unmarshalling logic to skip empty objects.
Another solution would be to create related structs locally and providing proper JSON annotations to fields like TS.
