### ISSUE TITLE
7g.79gb does not work as expected.

### ISSUE THREAD

**Issue by houms-sony** [nebuly-ai/nos#51]
using gpu-operator (helm 23.9.1), and nos (helm 0.1.2)

I have an issue with nvidia.com/mig-7g.79gb. when specifying it it causes nos to create the mig configuration as expected, but it seems to be specified  as nvidia.com/mig-7g.80gb as shown in log below from nvidia-device-plugin.

```
I0312 23:04:34.682199       1 server.go:165] Starting GRPC server for 'nvidia.com/mig-7g.80gb'
I0312 23:04:34.682673       1 server.go:117] Starting to serve 'nvidia.com/mig-7g.80gb' on /var/lib/kubelet/device-plugins/nvidia-mig-7g.80gb.sock
I0312 23:04:34.684745       1 server.go:125] Registered device plugin for 'nvidia.com/mig-7g.80gb' with Kubelet
````

Additionally, the labels created on the node look like this 

![Screenshot_20240312_162714](https://github.com/nebuly-ai/nos/assets/113714020/4579a95c-6005-426c-9638-593f54abce93)

But the issue is because we specified nvidia.com/mig-7g.79gb the pod stays in pending. Note the config below (all other nvidia examples commented out below work expect 7g.79gb. 

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-test-7g80g
spec:
  template:
    spec:
      runtimeClassName: nvidia
      restartPolicy: Never
      containers:
      - name: nvidia
        image: nvidia/cuda:12.3.2-devel-ubuntu22.04
        command: ["sleep", "12000"]
        resources:
          limits:
            nvidia.com/mig-7g.79gb: 1
            #nvidia.com/mig-1g.10gb: 1
            #nvidia.com/mig-2g.20gb: 1
            #nvidia.com/mig-4g.40gb: 1
```

I tried adding 7g.80gb to allowedGeometries, but it did not work as expected. Briefly looked at code and see https://github.com/nebuly-ai/nos/blob/main/pkg/gpu/mig/known_configs.go#L93, so not sure if I missed something, or if there is a way to get the desired behavior?
