### ISSUE TITLE
How to configure sharing.mps for individual nodes

### ISSUE THREAD

**Issue by amouu** [nebuly-ai/nos#53]
```
sharing:
  mps: 
    failRequestsGreaterThanOne: true
    resources:
      - name: nvidia.com/gpu
        rename: nvidia.com/gpu-2gb
        memoryGB: 2
        replicas: 2
        devices: ["0"]
```

Can this configuration be applied to individual nodes as specified above?
